schema_version = 1
version = "0.5.0"
published_at = "2026-10-04T15:16:08Z"

[firmware.app]
filename = "Wireless_power_emergency_stop_app_v0.5.0.bin"
offset = "0x10000"
size = 1005216
sha256 = "0aece639bc6c3408ec98d5d93154240408cd3146ca2dba0ca69c75a76fc4eb13"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_emergency_stop@b4c448520521b76102ec1f3225ae857621cc123d/firmware/v0.5.0/Wireless_power_emergency_stop_app_v0.5.0.bin"

[firmware.merged]
filename = "Wireless_power_emergency_stop_merged_v0.5.0.bin"
offset = "0x0"
size = 1070752
sha256 = "06804e6793cffc8f9fb10588f5c3637f993e64cbc007d2d48e86c081b3d03bbd"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_emergency_stop@b4c448520521b76102ec1f3225ae857621cc123d/firmware/v0.5.0/Wireless_power_emergency_stop_merged_v0.5.0.bin"
