"""Generate approved product UI assets. Run on Windows with Pillow and system fonts."""
from pathlib import Path
import runpy
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parents[1]
p=runpy.run_path(str(ROOT/'scripts/product_ui_layout.py'))
state=p['state_page']; confirm=p['confirm'];menu=p['menu'];rail=p['rail']

def pack(im):
 return [sum(1<<bit for bit in range(8) if page*8+bit<im.height and im.getpixel((x,page*8+bit))) for page in range((im.height+7)//8) for x in range(im.width)]
def array(data):return '{'+','.join(map(str,data))+'}'
output=['// Generated by scripts/generate_product_ui.py; approved 128x64 layout.','#pragma once','#include <stdint.h>']
def emit(name,images,shape):
 output.append('static const uint8_t '+name+shape+' = {'+','.join(array(pack(im)) for im in images)+'};')
# Order follows EmergencyRemote::State, then OTP/OVP/UVP/OCP and pairing.
statuses=[
 state('ready','准备就绪','等待操作','待确认'),
 state('check','已关闭','急停已生效'),state('check','已开启','返回数据','开启'),
 state('stopping','正在关闭','等待确认','待确认'),state('starting','正在开启','等待确认','待确认'),
 state('short_check','短路检测','暂未开启'),state('short_fault','检测到短路','检查负载'),
 state('protected','保护触发','检查对端'),state('offline','通信中断','请稍候','未连接'),
 state('unpaired','尚未配对','长按菜单','未连接'),state('protected','开启拒绝','检查对端'),
 state('starting','冷却等待','稍后再试'),state('starting','设备忙碌','稍后再试'),
 state('protected','尚未就绪','检查对端'),state('protected','检测异常','检查设备'),
 state('temperature','温度保护','等待降温'),state('overvoltage','过压保护','检查电源'),
 state('undervoltage','欠压保护','检查电源'),state('overcurrent','过流保护','检查负载'),
 state('unpaired','正在配对','对端配对','未连接')]
emit('kProductStates',statuses,'[20][1024]')
emit('kProductRetry',[state('stopping','关闭未确认','仍在重试','待确认')],'[1][1024]')
charge=Image.new('1',(128,64));ImageDraw.Draw(charge).polygon([(103,46),(96,54),(101,54),(98,59),(108,51),(102,51)],fill=1)
emit('kProductCharge',[charge],'[1][1024]')
messages=[state('moon','准备休眠','按键可唤醒'),state('usb','无法休眠','请拔电源'),
 state('on','无法休眠','请先关闭','开启'),state('stopping','无法休眠','等待确认','待确认'),
 state('starting','暂不可操作','等待完成','待确认'),state('ready','请松开按键','随后操作'),
 state('sun','常亮已开','设置已保存'),state('protected','保存失败','重新操作'),
 state('unpaired','正在配对','对端配对','未连接'),state('unpaired','删除配对','再次确认'),
 state('sun','常亮已关','设置已保存'),state('battery','电量偏低','请接电源',soc=8)]
emit('kProductMessages',messages,'[12][1024]')
menus=[]; confirms=[]
for mode in [False,True]:
 p['MENU'][1]='常亮已开' if mode else '常亮已关'
 menus.extend(menu(i) for i in range(7))
 for title,symbol in [('返回主页','return'),('关闭常亮' if mode else '开启常亮','sun'),('进入休眠','moon'),('关闭输出','off'),('开始配对','unpaired'),('重新配对','unpaired'),('设备状态','info'),('删除配对','unpaired')]:
  confirms.extend([confirm(title,symbol,False),confirm(title,symbol,True)])
emit('kProductMenus',menus,'[14][1024]')
emit('kProductConfirms',confirms,'[32][1024]')
rails=[]
for status in ['关闭','开启','待确认','未连接']:
 im=Image.new('1',(128,64));rail(im,status)
 d=ImageDraw.Draw(im);d.rectangle((81,45,119,60),fill=0)
 rails.append(im)
emit('kProductRails',rails,'[4][1024]')
# Generate the approved home layout directly; no draft images are needed.
home=Image.new('1',(128,64))
d=ImageDraw.Draw(home)
# The visible numeric glyphs are 12 pixels high at row tops 5/26/47.
# Align each complete rounded unit badge to that ink box, rather than a font baseline.
unit_pixels={
 'V':['#.....#','#.....#','.#...#.','.#...#.','.#...#.','..#.#..','..#.#..','...#...'],
 'A':['...#...','..#.#..','..#.#..','.#...#.','.#...#.','.#####.','#.....#','#.....#'],
 'W':['#.....#','#.....#','#.....#','#..#..#','#..#..#','#.#.#.#','#.#.#.#','.#...#.'],
}
for row,label in enumerate('VAW'):
 top=4+row*21
 d.rounded_rectangle((54,top,68,top+13),radius=3,outline=1)
 # Symmetric native pixel symbols avoid unequal font side bearings:
 # all three seven-pixel ink boxes share the same center and height.
 for y,line in enumerate(unit_pixels[label]):
  assert len(line)==7 and line==line[::-1],label
  for x,value in enumerate(line):
   if value=='#':d.point((58+x,top+3+y),fill=1)
emit('kProductHome',[home],'[1][1024]')
for name,label,y,font in [('kHistoryFooter','上次原因',54,p['FOOT']),('kInfoTitle','电池电压',3,p['CN']),('kInfoFooter','按键返回',52,p['FOOT']),('kFailureHint','短按重试',52,p['CN']),('kSleepCountdown','秒后休眠',33,p['FOOT']),('kBlankCountdown','秒后熄屏',33,p['FOOT']),('kInfoUsb','外部供电',40,p['FOOT']),('kInfoBattery','电池供电',40,p['FOOT'])]:
 im=Image.new('1',(128,64));p['center'](ImageDraw.Draw(im),label,y,font)
 emit(name,[im],'[1][1024]')
# Regular numeric font with identical baseline and narrow decimal point as approved preview.
font=ImageFont.truetype('C:/Windows/Fonts/consola.ttf',19)
glyphs=[]
for ch in '0123456789.-':
 w=4 if ch=='.' else 9
 tile=Image.new('1',(20,22));d=ImageDraw.Draw(tile);b=font.getbbox(ch)
 d.text((1-b[0],-font.getbbox('0')[1]),ch,font=font,fill=1)
 bb=tile.getbbox();im=Image.new('1',(9,16))
 if bb:im.paste(tile.crop((bb[0],0,bb[2],16)),(0,0))
 assert not tile.crop((0,16,20,22)).getbbox(),ch
 glyphs.append(im)
emit('kProductDigits',glyphs,'[12][18]')
font=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',12)
glyphs=[];widths=[]
for ch in '0123456789%?V':
 b=font.getbbox(ch);width=b[2]-b[0];widths.append(width)
 im=Image.new('1',(12,16));d=ImageDraw.Draw(im);d.text((-b[0],-font.getbbox('0')[1]),ch,font=font,fill=1);glyphs.append(im)
emit('kSocGlyphs',glyphs,'[13][24]')
output.append('static const uint8_t kSocWidths[13] = '+array(widths)+';')
font=ImageFont.truetype('C:/Windows/Fonts/consola.ttf',24)
glyphs=[]
for ch in '0123456789':
 im=Image.new('1',(13,24));d=ImageDraw.Draw(im);b=font.getbbox(ch)
 d.text((-b[0],-font.getbbox('0')[1]),ch,font=font,fill=1);glyphs.append(im)
emit('kCountdownDigits',glyphs,'[10][39]')
(ROOT/'components/app/emergency_ui/product_pages.h').write_text('\n'.join(output)+'\n',encoding='utf-8')
print('Product bitmap assets generated; all templates 128x64 with text boundary checks.')
