"""Generate static Chinese status labels and bitmap ASCII glyphs for live SH1106 UI."""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
from generate_diagnostic_pages import icon, FONT, SMALL, ROOT, centered

def pack(im):
    return [sum((1 << bit) if page*8+bit < im.height and im.getpixel((x,page*8+bit)) else 0
                for bit in range(8)) for page in range((im.height+7)//8) for x in range(im.width)]

def array(data):
    return '{'+','.join(str(n) for n in data)+'}'

pages = [
    ('ready','就绪','等待操作',''),
    ('off','输出关闭','已确认','急停保持关闭'),
    ('on','输出开启','已确认',''),
    ('stopping','正在关闭','等待确认','通信失败将重试'),
    ('starting','正在开启','检测中','等待对端确认'),
    ('short_check','短路检测','暂未开启','正在检查负载'),
    ('short_fault','禁止开启','检测到短路','请检查负载'),
    ('protected','保护触发','禁止开启','请检查功率计'),
    ('offline','通信中断','状态未确认','请检查功率计'),
    ('unpaired','尚未配对','无法控制','请先完成配对'),
    ('protected','开启拒绝','原因未提供','请检查功率计'),
    ('starting','冷却等待','暂未开启','稍后重新操作'),
    ('starting','设备忙碌','暂未开启','稍后重新操作'),
    ('protected','尚未就绪','暂未开启','请检查功率计'),
    ('short_fault','检测异常','禁止开启','请检查功率计'),
    ('protected','温度保护','输出关闭','请等待温度恢复'),
    ('protected','过压保护','输出关闭','请检查输入电压'),
    ('protected','欠压保护','输出关闭','请检查输入电压'),
    ('protected','过流保护','输出关闭','请检查负载'),
]
images=[]
for name,title,detail,footer in pages:
    im=Image.new('1',(128,64));d=ImageDraw.Draw(im)
    d.text((1,-1),'急停开关',font=SMALL,fill=1);d.line((0,12,127,12),fill=1)
    im.paste(icon(name),(3,15))
    for y,text,font in [(18,title,FONT),(38,detail,SMALL)]:
        box=d.textbbox((0,0),text,font=font)
        assert box[2]-box[0]<=68,text
        d.text((58-box[0],y-box[1]),text,font=font,fill=1)
    centered(d,52,footer,SMALL)
    images.append(im)
meter=Image.new('1',(128,64));d=ImageDraw.Draw(meter)
d.text((1,-1),'实时数据',font=SMALL,fill=1)
d.line((0,12,127,12),fill=1);d.line((0,54,127,54),fill=1)
for y,unit in [(18,'V'),(38,'A')]:
    box=d.textbbox((0,0),unit,font=FONT);d.text((108-box[0],y-box[1]),unit,font=FONT,fill=1)
large=ImageFont.truetype('C:/Windows/Fonts/consolab.ttf',20)
small=ImageFont.truetype('C:/Windows/Fonts/consola.ttf',10)
def glyphs(font,width,height):
    result=[]
    for code in range(32,127):
        im=Image.new('1',(width,height));d=ImageDraw.Draw(im)
        box=d.textbbox((0,0),chr(code),font=font)
        d.text((-box[0],-font.getbbox('0')[1]),chr(code),font=font,fill=1)
        result.append(array(pack(im)))
    return ',\n'.join(result)
out=['// Generated by scripts/generate_live_ui.py', '#pragma once','#include <stdint.h>',
     'static const uint8_t kLivePages[][1024] = {'+','.join(array(pack(im)) for im in images)+'};',
     'static const uint8_t kLiveMeter[1024] = '+array(pack(meter))+';',
     'static const uint8_t kLargeGlyphs[95][36] = {'+glyphs(large,12,24)+'};',
     'static const uint8_t kSmallGlyphs[95][12] = {'+glyphs(small,6,12)+'};']
(ROOT/'components/app/emergency_ui/private_include/live_pages.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
sheet=Image.new('RGB',(4*384,5*210),'#202329')
for n,im in enumerate(images):
    sheet.paste(im.convert('RGB').resize((384,192),Image.Resampling.NEAREST),((n%4)*384,(n//4)*210))
preview_root = ROOT/'tmp/ui-previews'
preview_root.mkdir(parents=True, exist_ok=True)
sheet.save(preview_root/'live-ui-preview.png')
