"""Generate Chinese menu labels; selection and status remain dynamic."""
from PIL import Image, ImageDraw
from generate_diagnostic_pages import FONT, SMALL, ROOT, icon, centered
from generate_live_ui import pack, array
items = ['返回数据', '常亮模式', '手动休眠', '关闭输出', '开始配对', '重新配对', '设备状态']
menus=[]; confirms=[]
for n, title in enumerate(items):
    im=Image.new('1',(128,64)); d=ImageDraw.Draw(im)
    d.text((1,-1),'设置菜单',font=SMALL,fill=1); d.line((0,12,127,12),fill=1)
    im.paste(icon(['ready','on','off','off','unpaired','unpaired','ready'][n]),(3,15))
    d.text((58,20),title,font=FONT,fill=1)
    centered(d,52,'短按选择 长按确认',SMALL); menus.append(im)
    im=Image.new('1',(128,64)); d=ImageDraw.Draw(im)
    centered(d,2,title,FONT); centered(d,24,'是否确认操作',SMALL)
    d.text((20,46),'取消',font=SMALL,fill=1); d.text((82,46),'确认',font=SMALL,fill=1)
    confirms.append(im)
messages=[]
for title, detail in [('正在休眠','按键或急停唤醒'),('无法休眠','请先拔下电源'),('无法休眠','请先关闭输出'),('无法休眠','输出状态未确认'),('暂不可操作','等待操作完成'),('请先松开按键','随后再操作'),('设置已保存','常亮模式'),('设置失败','请重新操作'),('正在配对','请开启功率计配对'),('再次确认','将删除原配对记录'),('连接失败','短按按键重试')]:
    im=Image.new('1',(128,64)); d=ImageDraw.Draw(im)
    im.paste(icon('off' if title=='正在休眠' else 'protected'),(3,12))
    d.text((56,17),title,font=SMALL,fill=1); centered(d,51,detail,SMALL); messages.append(im)
out=['// Generated by scripts/generate_runtime_ui.py','#pragma once','#include <stdint.h>']
for name,images in [('kMenuPages',menus),('kConfirmPages',confirms),('kMessagePages',messages)]:
    out.append('static const uint8_t '+name+'[][1024] = {'+','.join(array(pack(im)) for im in images)+'};')
(ROOT/'components/app/emergency_ui/runtime_pages.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
sheet=Image.new('RGB',(3*384,7*210),'#202329')
for n,im in enumerate(menus+messages):
    sheet.paste(im.convert('RGB').resize((384,192),Image.Resampling.NEAREST),((n%3)*384,(n//3)*210))
preview_root = ROOT/'tmp/ui-previews'
preview_root.mkdir(parents=True, exist_ok=True)
sheet.save(preview_root/'menu-ui-preview.png')
